<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Refugio.Domain\Refugio.Domain.csproj" />
    <ProjectReference Include="..\Refugio.Infrastructure\Refugio.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akka" Version="1.5.*" />
    <PackageReference Include="Akka.DependencyInjection" Version="1.5.*" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
